--================================[Creates the tables for HSQLDB database]====================================
CREATE TABLE PUBLIC.MSF_ADMIN_CONNECTIONS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONN_NAME LONGVARCHAR,
    ID_DATABASE_TYPE INTEGER,
    USER_NAME VARCHAR(100),
    PASSWORD VARCHAR(100),
    HOST VARCHAR(100),
    PORT INTEGER,
    DATABASE_NAME VARCHAR(100),
    SERVICE BOOLEAN,
    URL VARCHAR(100)
); 
