INSERT INTO COMPANY(NAME) VALUES('MELTSAN');
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(1, 'arivas', 'Armando Rivas', 28);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(1, 'ejimenez', 'Eduardo Rocha', 28);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(1, 'fgonzalez', 'Francisco Gonzalez', 28);

INSERT INTO COMPANY(NAME) VALUES('AXA');
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(2, 'agomez', 'Some user', 5);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(2, 'first', 'Another user', 65);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(2, 'second', 'Some more', 798);

INSERT INTO COMPANY(NAME) VALUES('HSBC');
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'achavez', 'Sachavez', 35);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'aramirez', 'aramirez', 65);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'aperez', 'aperez', 59);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'avaca', 'avaca', 50);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'aprieto', 'aprieto', 75);
INSERT INTO EMPLOYEE (ID_COMPANY, USER_NAME, FULL_NAME, AGE) VALUES(3, 'anievo', 'anievo', 55);