DROP TABLE EMPLOYEE;
DROP TABLE COMPANY;

--================================[Creates the tables for DERBY database]====================================
CREATE TABLE COMPANY (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME LONG VARCHAR,
    CONSTRAINT COMPANY_ID_PK PRIMARY KEY (ID)
); 

CREATE TABLE EMPLOYEE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_COMPANY INTEGER NOT NULL,
    USER_NAME LONG VARCHAR,
    FULL_NAME LONG VARCHAR,
    AGE INTEGER,
    CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY (ID),
    FOREIGN KEY (ID_COMPANY) REFERENCES COMPANY(ID)
);

--================================[Creates the tables for HSQLDB database]====================================
CREATE TABLE PUBLIC.COMPANY (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME LONGVARCHAR
); 

CREATE TABLE PUBLIC.EMPLOYEE (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMPANY INTEGER NOT NULL,
    USER_NAME LONGVARCHAR,
    FULL_NAME LONGVARCHAR,
    AGE INTEGER
);